config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#welcome'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/google_oauth2/callback' => 'sessions#omniauth_google'
  get '/auth/github/callback' => 'sessions#omniauth_github'
  
  # resources :genres 
  resources :comments, only: [:index, :new, :create]
  resources :books
  resources :users do
    resources :books, only: [:index, :new, :create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :genre
  belongs_to :user
  has_many :comments
  has_many :users, through: :comments
  has_one_attached :image
  validates :title, :author, :condition, :price, presence: true
  # accepts_nested_attributes_for :genre

  def genre_attributes=(attributes)
    self.genre = Genre.find_or_create_by(attributes) if !attributes['name'].empty?
    self.genre
  end

  def self.order_by_price
    order(price: :desc)
  end

  def self.by_genre(genre_id)
    where(genre: genre_id)
  end

  scope :recent_books, -> { order(created_at: :desc) }





end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
  belongs_to :user
  validates :content, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :books
    validates :name, presence: true
    validates :name, uniqueness: true 

end

app/models/user.rb
class User < ApplicationRecord
    has_many :books
    has_many :comments
    has_many :commented_books, through: :comments, source: :book

    has_secure_password
    validates :email, :username, presence: true 
    validates :email, uniqueness: true 

    def self.google_omniauth(auth)
      self.find_or_create_by(email: auth[:info][:email]) do |user|
        user.username = auth[:info][:name]
        user.password = SecureRandom.hex
      end
    end

    def self.github_omniauth(auth)
      self.find_or_create_by(email: auth[:info][:email]) do |user|
        user.username = auth[:info][:nickname]
        user.password = SecureRandom.hex
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    helper_method :current_user, :logged_in?, :redirect_home_if_not_logged_in

    private
    
    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end
    
    def logged_in?
        !!current_user
    end

    def redirect_home_if_not_logged_in
        if !logged_in?
            redirect_to root_path
        end
    end

    # def redirect_home_if_not_current_user_nested
    #     redirect_to root_path if current_user.id.to_s != params[:user_id]
    # end

    # def redirect_home_if_not_current_user
    #     redirect_to root_path if current_user.id.to_s != params[:id]
    # end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    before_action :redirect_home_if_not_logged_in
    before_action :find_book, only: [:show, :edit, :update, :destroy]

    def new
      if current_user.id.to_s == params[:user_id]
        @book = Book.new
        @book.build_genre
      else
        redirect_to root_path
      end
    end

    def create
      @book = current_user.books.build(book_params) 
      if @book.save
        @book.image.purge
        @book.image.attach(params[:book][:image])
        redirect_to books_path
      else
        @book.build_genre
        render :new
      end
    end

    def index
      if @user = User.find_by_id(params[:user_id])
        if !params[:genre].blank?
          @books = Book.by_genre(params[:genre])
        else
          @books = @user.books.recent_books
        end
      else
        if !params[:genre].blank?
          @books = Book.by_genre(params[:genre])
        else
          @books = Book.recent_books
        end
      end
    end

    def show
      if @book
        @comments = @book.comments
      else
        redirect_to root_path
      end
    end

    def edit
      if !current_user.books.include?(@book)
        redirect_to user_books_path(current_user)
      end
    end

    def update
      if @book.update(book_params)
        @book.image.purge
        @book.image.attach(params[:book][:image])
        redirect_to user_books_path(current_user)
      else
        render :edit
      end
    end

    def destroy
      @book.delete
      redirect_to user_books_path(current_user)
    end

    private

    def book_params
        params.require(:book).permit(:title, :author, :condition, :price, :genre_id, genre_attributes: [:name])
    end

    def find_book
      @book = Book.find_by_id(params[:id])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def new

    end

    def create
      @book = Book.find_by_id(params[:comment][:book_id])
      @comment = current_user.comments.build(comment_params)
      if @comment.save
        redirect_to book_path(@book)
      else
        redirect_to book_path(@book)
      end
    end

    def index

    end

    private

    def comment_params
        params.require(:comment).permit(:content, :book_id)
    end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def welcome
        
    end

    def new

    end
    
    def create
      @user = User.find_by(username: params[:user][:username])
      if @user && @user.authenticate(params[:user][:password])
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        flash[:message] = "Invalid Credentials. Please try again."
        redirect_to login_path
      end
    end

    def destroy
      current_user
      session.clear
      redirect_to root_path
    end

    def omniauth_google
      @user = User.google_omniauth(auth)
        if @user.save
          session[:user_id] = @user.id
          redirect_to books_path
        else
          redirect_to root_path
        end
    end

    def omniauth_github
      @user = User.github_omniauth(auth)
        if @user.save
          session[:user_id] = @user.id
          redirect_to books_path
        else
          @error = "Email or Username Missing"
          render :welcome
        end
    end

    private

    def auth
      request.env['omniauth.auth']
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
      @user = User.new
    end

    def create
       @user = User.new(user_params)
       if @user.save
          session[:user_id] = @user.id
          redirect_to books_path
       else
          render :new
       end
    end

    def show
      if logged_in?
        if current_user.id.to_s == params[:id]
         @user = User.find_by_id(params[:id])
         @commented_books = @user.commented_books
         else
         redirect_to user_path(current_user)
         end
      else
         redirect_to root_path
      end
    end



    private

    def user_params
        params.require(:user).permit(:email, :username, :password)
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= render partial: 'layouts/errors', locals: {obj: @book}  %>

<div class="book-form">
  <div class="form">
<%= form_for @book do |f| %>
  
  <%= f.label :title %>
  <%= f.text_field :title%>
  <br>
  <br>
  <%= f.label :author %>
  <%= f.text_field :author%>
  <br>
  <br>
  <%= f.label :image %> 
  <%= f.file_field :image %>
  <br>
  <br>
  <%= f.label "Select a Genre" %>
  <%= f.collection_select(:genre_id, Genre.all, :id, :name, prompt: true) %>
  <span>or Add a Genre</span>
  <%= f.fields_for :genre do |g| %>
    <%= g.text_field :name %>
  <% end %>
  <br>
  <br>
  <%= f.label :condition %>
  <%= f.select :condition, ["New", "Like New", "Good", "Fair", "Poor"] %>
  <br>
  <br>
  <%= f.label :price, "$" %>
  <%= f.number_field :price, in: 1..1000, step: 1 %>  
  <br>
  <br>
  <%= f.submit %>
<% end %>
  </div>
</div>

app/views/books/edit.html.erb
<h2>Edit Your Listing</h2>

<%= render partial: 'form'%>

app/views/books/index.html.erb
<% if params[:user_id] %>
  <h2>Books for Sale by <%= @user.username %></h2>
<% else %>
  <h2>Books for Sale</h2>
 <% end %>

<div>
  <%= form_tag("/books", method: "get") do %>
    <%= select_tag "genre", options_from_collection_for_select(Genre.all, "id", "name"), { prompt: 'Select Genre' } %>
    <%= submit_tag "Filter" %>
  <% end %>
</div>

<div class="book-cards">
<% @books.each do |book| %>
<div class="book-card">
  <ul>
    <li>
      <div class="book-title">
      <%= link_to book.title, book_path(book) %> <br>
      <i>by</i> <%= book.author %>
      </div>
      <div class="img">
      <% if book.image.attached? %>
        <%= image_tag url_for(book.image) %> 
      <% end %>
      </div>
      <div class="book-details">
      Condition: <%= book.condition %>
      <br>
      <br>
      Price: $<%= book.price %>
      <br>
      <br>
      Posted: <%= book.created_at.strftime("%b %d, %Y")%>
      </div>
    </li>
  </ul>
</div>
<% end %>
</div>

app/views/books/new.html.erb
<h2>List A Book</h2>

<%= render partial: 'form'%>

app/views/books/show.html.erb
<div class="title">
<h2><%= @book.title %></h2>
<i>by</i> <b><%= @book.author %></b>
<br>
</div>
<div class="img">
 <% if @book.image.attached? %>
   <%= image_tag url_for(@book.image) %>
 <% end %>
 </div>
<br>
<br>
<div class="details">
Genre: <%= @book.genre.name if @book.genre %>
<br>
<br>
Condition: <%= @book.condition %>
<br>
<br>
Price: $<%= @book.price %>
<br>
<br>
Posted on: <%= @book.created_at.strftime("%b %d, %Y")%>
<br>
<br>
Seller: <%= link_to @book.user.username, user_books_path(@book.user)  %>
<br><br>
</div>

Comments:
  <ul>
  <% @comments.each do |comment| %>
  <li>
    "<%= comment.content %>" - <%= comment.user.username %> (<%= comment.created_at.strftime("%m/%d/%Y") %>)
    <br><br>
   </li>
  <% end %>
  </ul>


<br><br>
<%= form_for @book.comments.build do |f| %>
    <%= f.label :content, "Post a comment: " %>
    <%= f.text_field :content %>
    <%= f.hidden_field :book_id %>
  <%= f.submit "Post" %>
<% end %>
<br>
<br>
<% if current_user == @book.user %>
  <%= link_to "Edit", edit_book_path(@book) %> | <%= link_to "Delete", @book, method: "delete", data: { confirm: "Are you sure?" } %>
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <% obj.errors.full_messages.each do |msg| %>
      <p><i><%= msg %></i></p>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookmark</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('BlackwithBookShelfIconEducationLogo.png') %>
  </head>

  <body>
    <div class="topnav">
      <%= link_to "Home", root_path %> 
    <% if logged_in? %>
      <%= link_to "List A Book", new_user_book_path(current_user) %> |
      <%= link_to "Books For Sale", books_path %> |
      <%= link_to "My Books", user_books_path(current_user) %> |
      <%= link_to "Profile", user_path(session[:user_id])%> |
      <%= link_to "Logout", logout_path, method: "delete" %>
    <% else %>
      <%= link_to "Login", login_path %> |
      <%= link_to "Sign Up", signup_path %> |
      <%= link_to "Log In With Google", '/auth/google_oauth2', method: :post %> |
      <%= link_to "Log In With Github", '/auth/github', method: :post %>
    <% end %>
    </div>

    

    <div class="wrapper">
    <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render partial: 'layouts/errors', locals: {obj: @user}  %>

<%= form_for @user, url: '/signup' do |f| %>

  <%= f.label :username %>
  <br>
  <%= f.text_field :username%>
  <br>
  <br>
  <%= f.label :email %>
  <br>
  <%= f.email_field :email%>
  <br>
  <br>
  <%= f.label :password %>
  <br>
  <%= f.password_field :password%>
  <br>
  <br>
  <%= f.submit "Sign Up" %>

<% end %>

app/views/users/show.html.erb
<h2>Welcome <%= @user.username %>!</h2>

<div class="user-details">

<p>Email: <%= @user.email %></p>
<p>Books Listed: <%= @user.books.count %></p>

<p>Joined: <%= @user.created_at.strftime("%b %d, %Y") %></p>
</div>

<p style="text-align: left;"><b>Books I've Commented On:</b></p>

<div class="book-cards">
<% @commented_books.each do |book| %>
<div class="book-card">
  <ul>
    <li>
      <div class="book-title">
      <%= link_to book.title, book_path(book) %> <br>
      <i>by</i> <%= book.author %>
      </div>
      <div class="img">
      <% if book.image.attached? %>
        <%= image_tag url_for(book.image) %> 
      <% end %>
      </div>
    </li>
  </ul>
</div>
<% end %>
</div>